### ISSUE TITLE
does this work on unraid?

### ISSUE THREAD

**Issue by muziling** [FOXBI/tr_st#12]
Try to add an vm on unraid,  set 1st controller to 10G disk for install dsm, 2nd controller to tinycore loader
build ds918p,  reboot an modify hd0,msdos3 to hd1,msdos3,  SataPortMap=6 and boot to go,
open dsm web install page, select ds918p pat,  hint to format disk,  format failed .

**Comment by suzukua** [comment]
+1

**Comment by FOXBI** [comment]
Please check again whether the following items and conditions are met.

SATA0 (0:0) - Data Disk
SATA1 (1:0) - Tinycore Disk

SataPortMap=6
DiskIdxMap=0
SasIdxMap=0

If you add esxi's paravirtual SCSI controller, it is recommended to set SataPortMap=1.

**Comment by muziling** [comment]
Finally resolved,  Data Disk allocate 10G is not enough,  allocate 25G install success

**Comment by FOXBI** [comment]
I'm glad it's been resolved.
